import fs from 'fs';
const D = JSON.parse(fs.readFileSync('data.json','utf8'));
const pd = D.definitions.pointDefinitions;

const SECTION_TH = {
  SCREEN_RESULTS_SUBTITLE_VITALS:          'สัญญาณชีพ',
  SCREEN_RESULTS_SUBTITLE_PHYSIOLOGICAL:   'สรีรวิทยา',
  SCREEN_RESULTS_SUBTITLE_MENTAL:          'สุขภาพจิต',
  SCREEN_RESULTS_SUBTITLE_PHYSICAL:        'สภาพร่างกาย',
  SCREEN_RESULTS_SUBTITLE_GENERALRISKS:    'ความเสี่ยงทั่วไป',
  SCREEN_RESULTS_SUBTITLE_METABOLICRISKS:  'ความเสี่ยงทางเมแทบอลิก',
  SCREEN_RESULTS_SUBTITLE_BLOODBIOMARKERS: 'ตัวชี้วัดทางเลือด',
  SCREEN_RESULTS_SUBTITLE_OVERALL:         'ภาพรวม',
};

const LABEL_TH = {
  HR_BPM:'อัตราการเต้นของหัวใจ', IHB_COUNT:'หัวใจเต้นผิดจังหวะ', BR_BPM:'อัตราการหายใจ',
  BP_SYSTOLIC:'ความดันโลหิตตัวบน', BP_DIASTOLIC:'ความดันโลหิตตัวล่าง', TEMPERATURE_SENSOR:'อุณหภูมิร่างกาย',
  HRV_SDNN:'ความแปรปรวนหัวใจ (HRV)', BP_RPP:'ภาระงานของหัวใจ', VITALITY:'ดัชนีความกระปรี้กระเปร่า',
  MSI:'ดัชนีความเครียด', SLEEP_QUALITY:'ดัชนีคุณภาพการนอน', ANXIETY_INDEX:'ดัชนีความวิตกกังวล',
  AGE:'อายุผิวหน้า', BMI_CALC:'ดัชนีมวลกาย (BMI)', ABSI:'ดัชนีรูปร่าง (ABSI)', WAIST_TO_HEIGHT:'สัดส่วนเอวต่อส่วนสูง',
  BP_CVD:'โรคหัวใจและหลอดเลือด', BP_HEART_ATTACK:'หัวใจวาย', BP_STROKE:'โรคหลอดเลือดสมอง',
  OVERALL_METABOLIC_RISK_PROB:'เมตาบอลิกโดยรวม', HPT_RISK_PROB:'ความดันโลหิตสูง',
  DBT_RISK_PROB:'เบาหวานชนิดที่ 2', HDLTC_RISK_PROB:'คอเลสเตอรอลสูง',
  TG_RISK_PROB:'ไตรกลีเซอไรด์สูง', FLD_RISK_PROB:'ไขมันพอกตับ',
  HBA1C_RISK_PROB:'ความเสี่ยงน้ำตาลสะสม (HbA1c)', MFBG_RISK_PROB:'ความเสี่ยงน้ำตาลในเลือด',
  HEALTH_SCORE:'คะแนนสุขภาพโดยรวม',
  VITAL_SCORE:'สัญญาณชีพ', PHYSIO_SCORE:'สรีรวิทยา', MENTAL_SCORE:'สุขภาพจิต',
  PHYSICAL_SCORE:'สภาพร่างกาย', RISKS_SCORE:'ความเสี่ยง',
};

const UNIT_TH = { BPM:'ครั้ง/นาที', BRPM:'ครั้ง/นาที', MMHG:'mmHg', CELSIUS:'°C',
  MILLISECONDS:'ms', DECIBELS:'dB', KG_M2:'kg/m²', PERCENT:'%' };

const sections = D.sections.map(sec => ({
  key: sec.titleLocalizationKey,
  title: SECTION_TH[sec.titleLocalizationKey] ?? sec.titleLocalizationKey,
  points: sec.pointsIDs.filter(id => pd[id]).map(id => {
    const d = pd[id];
    return {
      id,
      label: LABEL_TH[id] ?? id,
      unit: UNIT_TH[d.units] ?? '',
      dp: d.decimalPlaces ?? 1,
      lo: d.lowerBound, hi: d.upperBound,
      segments: (d.scales?.default?.segments ?? []).map(s => ({min:s.min, max:s.max, c:s.color})),
    };
  }),
}));

const missing = Object.keys(pd).filter(id => !sections.some(s=>s.points.some(p=>p.id===id)));
const out = `// generated by gen-points.mjs from the site's own data.js - do not hand-edit\n`
  + `export const SECTIONS = ${JSON.stringify(sections, null, 2)}\n`;
fs.writeFileSync('lib/points.mjs', out);
console.log('sections:', sections.length, '| points:', sections.reduce((n,s)=>n+s.points.length,0));
console.log('points in data.js not placed in any section:', missing.join(', ') || '(none)');
console.log('labels still untranslated:', sections.flatMap(s=>s.points).filter(p=>p.label===p.id).map(p=>p.id).join(', ')||'(none)');
