// generated by gen-points.mjs from the site's own data.js - do not hand-edit
export const SECTIONS = [
  {
    "key": "SCREEN_RESULTS_SUBTITLE_VITALS",
    "title": "สัญญาณชีพ",
    "points": [
      {
        "id": "HR_BPM",
        "label": "อัตราการเต้นของหัวใจ",
        "unit": "ครั้ง/นาที",
        "dp": 0,
        "lo": 40,
        "hi": 140,
        "segments": [
          {
            "min": 20,
            "max": 60,
            "c": "yellow"
          },
          {
            "min": 60,
            "max": 100,
            "c": "green"
          },
          {
            "min": 100,
            "max": 140,
            "c": "yellow"
          }
        ]
      },
      {
        "id": "IHB_COUNT",
        "label": "หัวใจเต้นผิดจังหวะ",
        "unit": "",
        "dp": 0,
        "lo": 0,
        "hi": 10,
        "segments": []
      },
      {
        "id": "BR_BPM",
        "label": "อัตราการหายใจ",
        "unit": "ครั้ง/นาที",
        "dp": 0,
        "lo": 5,
        "hi": 35,
        "segments": [
          {
            "min": 1.2,
            "max": 12,
            "c": "yellow"
          },
          {
            "min": 12,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 35,
            "c": "yellow"
          }
        ]
      },
      {
        "id": "BP_SYSTOLIC",
        "label": "ความดันโลหิตตัวบน",
        "unit": "mmHg",
        "dp": 0,
        "lo": 30,
        "hi": 180,
        "segments": [
          {
            "min": 45,
            "max": 90,
            "c": "yellow"
          },
          {
            "min": 90,
            "max": 120,
            "c": "green"
          },
          {
            "min": 120,
            "max": 130,
            "c": "lightGreen"
          },
          {
            "min": 130,
            "max": 140,
            "c": "yellow"
          },
          {
            "min": 140,
            "max": 180,
            "c": "red"
          }
        ]
      },
      {
        "id": "BP_DIASTOLIC",
        "label": "ความดันโลหิตตัวล่าง",
        "unit": "mmHg",
        "dp": 0,
        "lo": 30,
        "hi": 120,
        "segments": [
          {
            "min": 30,
            "max": 60,
            "c": "yellow"
          },
          {
            "min": 60,
            "max": 70,
            "c": "green"
          },
          {
            "min": 70,
            "max": 80,
            "c": "lightGreen"
          },
          {
            "min": 80,
            "max": 90,
            "c": "yellow"
          },
          {
            "min": 90,
            "max": 120,
            "c": "red"
          }
        ]
      },
      {
        "id": "TEMPERATURE_SENSOR",
        "label": "อุณหภูมิร่างกาย",
        "unit": "°C",
        "dp": 1,
        "lo": 35,
        "hi": 41.5,
        "segments": [
          {
            "min": 30,
            "max": 36.5,
            "c": "lightGreen"
          },
          {
            "min": 36.5,
            "max": 37.5,
            "c": "green"
          },
          {
            "min": 37.5,
            "max": 39.5,
            "c": "yellow"
          },
          {
            "min": 39.5,
            "max": 41.5,
            "c": "lightRed"
          },
          {
            "min": 41.5,
            "max": 45,
            "c": "red"
          }
        ]
      }
    ]
  },
  {
    "key": "SCREEN_RESULTS_SUBTITLE_PHYSIOLOGICAL",
    "title": "สรีรวิทยา",
    "points": [
      {
        "id": "HRV_SDNN",
        "label": "ความแปรปรวนหัวใจ (HRV)",
        "unit": "ms",
        "dp": 1,
        "lo": 1,
        "hi": 80,
        "segments": [
          {
            "min": 1.1,
            "max": 10.8,
            "c": "red"
          },
          {
            "min": 10.8,
            "max": 16.4,
            "c": "lightRed"
          },
          {
            "min": 16.4,
            "max": 35.5,
            "c": "yellow"
          },
          {
            "min": 35.5,
            "max": 51.5,
            "c": "lightGreen"
          },
          {
            "min": 51.5,
            "max": 80,
            "c": "green"
          }
        ]
      },
      {
        "id": "BP_RPP",
        "label": "ภาระงานของหัวใจ",
        "unit": "dB",
        "dp": 2,
        "lo": 3.7,
        "hi": 4.3,
        "segments": [
          {
            "min": 3.71,
            "max": 3.8,
            "c": "green"
          },
          {
            "min": 3.8,
            "max": 3.9,
            "c": "lightGreen"
          },
          {
            "min": 3.9,
            "max": 4.08,
            "c": "yellow"
          },
          {
            "min": 4.08,
            "max": 4.18,
            "c": "lightRed"
          },
          {
            "min": 4.18,
            "max": 4.28,
            "c": "red"
          }
        ]
      },
      {
        "id": "VITALITY",
        "label": "ดัชนีความกระปรี้กระเปร่า",
        "unit": "",
        "dp": 1,
        "lo": 1,
        "hi": 5.9,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "red"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightRed"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightGreen"
          },
          {
            "min": 5,
            "max": 6,
            "c": "green"
          }
        ]
      }
    ]
  },
  {
    "key": "SCREEN_RESULTS_SUBTITLE_MENTAL",
    "title": "สุขภาพจิต",
    "points": [
      {
        "id": "MSI",
        "label": "ดัชนีความเครียด",
        "unit": "",
        "dp": 1,
        "lo": 1,
        "hi": 5.9,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "green"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightGreen"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightRed"
          },
          {
            "min": 5,
            "max": 6,
            "c": "red"
          }
        ]
      },
      {
        "id": "SLEEP_QUALITY",
        "label": "ดัชนีคุณภาพการนอน",
        "unit": "",
        "dp": 1,
        "lo": 1,
        "hi": 5.9,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "red"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightRed"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightGreen"
          },
          {
            "min": 5,
            "max": 6,
            "c": "green"
          }
        ]
      },
      {
        "id": "ANXIETY_INDEX",
        "label": "ดัชนีความวิตกกังวล",
        "unit": "",
        "dp": 1,
        "lo": 1,
        "hi": 5.9,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "green"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightGreen"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightRed"
          },
          {
            "min": 5,
            "max": 6,
            "c": "red"
          }
        ]
      }
    ]
  },
  {
    "key": "SCREEN_RESULTS_SUBTITLE_PHYSICAL",
    "title": "สภาพร่างกาย",
    "points": [
      {
        "id": "AGE",
        "label": "อายุผิวหน้า",
        "unit": "",
        "dp": 0,
        "lo": 10,
        "hi": 100,
        "segments": []
      },
      {
        "id": "BMI_CALC",
        "label": "ดัชนีมวลกาย (BMI)",
        "unit": "kg/m²",
        "dp": 0,
        "lo": 10,
        "hi": 60,
        "segments": [
          {
            "min": 10,
            "max": 18.5,
            "c": "yellow"
          },
          {
            "min": 18.5,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 30,
            "c": "yellow"
          },
          {
            "min": 30,
            "max": 35,
            "c": "lightRed"
          },
          {
            "min": 35,
            "max": 60,
            "c": "red"
          }
        ]
      },
      {
        "id": "ABSI",
        "label": "ดัชนีรูปร่าง (ABSI)",
        "unit": "",
        "dp": 2,
        "lo": 6,
        "hi": 10,
        "segments": [
          {
            "min": 6.6,
            "max": 7.1,
            "c": "green"
          },
          {
            "min": 7.1,
            "max": 7.6,
            "c": "lightGreen"
          },
          {
            "min": 7.6,
            "max": 8.6,
            "c": "yellow"
          },
          {
            "min": 8.6,
            "max": 9.1,
            "c": "lightRed"
          },
          {
            "min": 9.1,
            "max": 9.6,
            "c": "red"
          }
        ]
      },
      {
        "id": "WAIST_TO_HEIGHT",
        "label": "สัดส่วนเอวต่อส่วนสูง",
        "unit": "%",
        "dp": 0,
        "lo": 25,
        "hi": 70,
        "segments": [
          {
            "min": 25,
            "max": 43,
            "c": "yellow"
          },
          {
            "min": 43,
            "max": 53,
            "c": "green"
          },
          {
            "min": 53,
            "max": 58,
            "c": "yellow"
          },
          {
            "min": 58,
            "max": 63,
            "c": "lightRed"
          },
          {
            "min": 63,
            "max": 75,
            "c": "red"
          }
        ]
      }
    ]
  },
  {
    "key": "SCREEN_RESULTS_SUBTITLE_GENERALRISKS",
    "title": "ความเสี่ยงทั่วไป (% โอกาสเกิด)",
    "points": [
      {
        "id": "BP_CVD",
        "label": "โรคหัวใจและหลอดเลือด",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 5,
            "c": "green"
          },
          {
            "min": 5,
            "max": 7.25,
            "c": "lightGreen"
          },
          {
            "min": 7.25,
            "max": 10,
            "c": "yellow"
          },
          {
            "min": 10,
            "max": 20,
            "c": "lightRed"
          },
          {
            "min": 20,
            "max": 100,
            "c": "red"
          }
        ]
      },
      {
        "id": "BP_HEART_ATTACK",
        "label": "หัวใจวาย",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 33,
        "segments": [
          {
            "min": 0,
            "max": 1.65,
            "c": "green"
          },
          {
            "min": 1.65,
            "max": 2.39,
            "c": "lightGreen"
          },
          {
            "min": 2.39,
            "max": 3.3,
            "c": "yellow"
          },
          {
            "min": 3.3,
            "max": 6.6,
            "c": "lightRed"
          },
          {
            "min": 6.6,
            "max": 33,
            "c": "red"
          }
        ]
      },
      {
        "id": "BP_STROKE",
        "label": "โรคหลอดเลือดสมอง",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 66,
        "segments": [
          {
            "min": 0,
            "max": 3.3,
            "c": "green"
          },
          {
            "min": 3.3,
            "max": 4.79,
            "c": "lightGreen"
          },
          {
            "min": 4.79,
            "max": 6.6,
            "c": "yellow"
          },
          {
            "min": 6.6,
            "max": 13.2,
            "c": "lightRed"
          },
          {
            "min": 13.2,
            "max": 66,
            "c": "red"
          }
        ]
      }
    ]
  },
  {
    "key": "SCREEN_RESULTS_SUBTITLE_METABOLICRISKS",
    "title": "ความเสี่ยงเมตาบอลิก (% โอกาสเกิด)",
    "points": [
      {
        "id": "OVERALL_METABOLIC_RISK_PROB",
        "label": "เมตาบอลิกโดยรวม",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 45,
            "c": "lightGreen"
          },
          {
            "min": 45,
            "max": 55,
            "c": "yellow"
          },
          {
            "min": 55,
            "max": 75,
            "c": "lightRed"
          },
          {
            "min": 75,
            "max": 100,
            "c": "red"
          }
        ]
      },
      {
        "id": "HPT_RISK_PROB",
        "label": "ความดันโลหิตสูง",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 45,
            "c": "lightGreen"
          },
          {
            "min": 45,
            "max": 55,
            "c": "yellow"
          },
          {
            "min": 55,
            "max": 75,
            "c": "lightRed"
          },
          {
            "min": 75,
            "max": 100,
            "c": "red"
          }
        ]
      },
      {
        "id": "DBT_RISK_PROB",
        "label": "เบาหวานชนิดที่ 2",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 45,
            "c": "lightGreen"
          },
          {
            "min": 45,
            "max": 55,
            "c": "yellow"
          },
          {
            "min": 55,
            "max": 75,
            "c": "lightRed"
          },
          {
            "min": 75,
            "max": 100,
            "c": "red"
          }
        ]
      },
      {
        "id": "HDLTC_RISK_PROB",
        "label": "คอเลสเตอรอลสูง",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 45,
            "c": "lightGreen"
          },
          {
            "min": 45,
            "max": 55,
            "c": "yellow"
          },
          {
            "min": 55,
            "max": 75,
            "c": "lightRed"
          },
          {
            "min": 75,
            "max": 100,
            "c": "red"
          }
        ]
      },
      {
        "id": "TG_RISK_PROB",
        "label": "ไตรกลีเซอไรด์สูง",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 45,
            "c": "lightGreen"
          },
          {
            "min": 45,
            "max": 55,
            "c": "yellow"
          },
          {
            "min": 55,
            "max": 75,
            "c": "lightRed"
          },
          {
            "min": 75,
            "max": 100,
            "c": "red"
          }
        ]
      },
      {
        "id": "FLD_RISK_PROB",
        "label": "ไขมันพอกตับ",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 45,
            "c": "lightGreen"
          },
          {
            "min": 45,
            "max": 55,
            "c": "yellow"
          },
          {
            "min": 55,
            "max": 75,
            "c": "lightRed"
          },
          {
            "min": 75,
            "max": 100,
            "c": "red"
          }
        ]
      }
    ]
  },
  {
    "key": "SCREEN_RESULTS_SUBTITLE_BLOODBIOMARKERS",
    "title": "ตัวชี้วัดทางเลือด",
    "points": [
      {
        "id": "HBA1C_RISK_PROB",
        "label": "ความเสี่ยงน้ำตาลสะสม (HbA1c)",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 45,
            "c": "lightGreen"
          },
          {
            "min": 45,
            "max": 55,
            "c": "yellow"
          },
          {
            "min": 55,
            "max": 75,
            "c": "lightRed"
          },
          {
            "min": 75,
            "max": 100,
            "c": "red"
          }
        ]
      },
      {
        "id": "MFBG_RISK_PROB",
        "label": "ความเสี่ยงน้ำตาลในเลือด",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 25,
            "c": "green"
          },
          {
            "min": 25,
            "max": 45,
            "c": "lightGreen"
          },
          {
            "min": 45,
            "max": 55,
            "c": "yellow"
          },
          {
            "min": 55,
            "max": 75,
            "c": "lightRed"
          },
          {
            "min": 75,
            "max": 100,
            "c": "red"
          }
        ]
      }
    ]
  },
  {
    "key": "SCREEN_RESULTS_SUBTITLE_OVERALL",
    "title": "ภาพรวม",
    "points": [
      {
        "id": "HEALTH_SCORE",
        "label": "คะแนนสุขภาพโดยรวม",
        "unit": "%",
        "dp": 0,
        "lo": 0,
        "hi": 100,
        "segments": [
          {
            "min": 0,
            "max": 20,
            "c": "red"
          },
          {
            "min": 20,
            "max": 40,
            "c": "lightRed"
          },
          {
            "min": 40,
            "max": 60,
            "c": "yellow"
          },
          {
            "min": 60,
            "max": 80,
            "c": "lightGreen"
          },
          {
            "min": 80,
            "max": 100,
            "c": "green"
          }
        ]
      },
      {
        "id": "VITAL_SCORE",
        "label": "สัญญาณชีพ",
        "unit": "",
        "dp": 0,
        "lo": 1,
        "hi": 5,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "red"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightRed"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightGreen"
          },
          {
            "min": 5,
            "max": 5,
            "c": "green"
          }
        ]
      },
      {
        "id": "PHYSIO_SCORE",
        "label": "สรีรวิทยา",
        "unit": "",
        "dp": 0,
        "lo": 1,
        "hi": 5,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "red"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightRed"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightGreen"
          },
          {
            "min": 5,
            "max": 5,
            "c": "green"
          }
        ]
      },
      {
        "id": "MENTAL_SCORE",
        "label": "สุขภาพจิต",
        "unit": "",
        "dp": 0,
        "lo": 1,
        "hi": 5,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "red"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightRed"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightGreen"
          },
          {
            "min": 5,
            "max": 5,
            "c": "green"
          }
        ]
      },
      {
        "id": "PHYSICAL_SCORE",
        "label": "สภาพร่างกาย",
        "unit": "",
        "dp": 0,
        "lo": 1,
        "hi": 5,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "red"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightRed"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightGreen"
          },
          {
            "min": 5,
            "max": 5,
            "c": "green"
          }
        ]
      },
      {
        "id": "RISKS_SCORE",
        "label": "ความเสี่ยง",
        "unit": "",
        "dp": 0,
        "lo": 1,
        "hi": 5,
        "segments": [
          {
            "min": 1,
            "max": 2,
            "c": "red"
          },
          {
            "min": 2,
            "max": 3,
            "c": "lightRed"
          },
          {
            "min": 3,
            "max": 4,
            "c": "yellow"
          },
          {
            "min": 4,
            "max": 5,
            "c": "lightGreen"
          },
          {
            "min": 5,
            "max": 5,
            "c": "green"
          }
        ]
      }
    ]
  }
]
